# Generated by Django 4.2.11 on 2024-04-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths'), ('English', 'English')], default='Physics', max_length=20),
        ),
    ]
