# Generated by Django 4.2.11 on 2024-04-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-teacher']},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-created_on']},
        ),
    ]
